# TP 1. Introduction à Python 
## PARTIE 1
<img src="http://media.giphy.com/media/2lbhL8dSGMh8I/giphy.gif"  width="300">


In [1]:
print("Hello world!")

Hello world!


## Plan de cette première séance :

   [- opérations mathématiques élémentaires](#1)
   
   [- variables élémentaires et types ](#2)
   
   [- les conteneurs](#3)
    
   [- structures de contrôle](#4)
   
   [- fonctions](#5)
   
   [- introduction à numpy](#6)

 <a id="1"></a>
 
# 1. Opérations mathématiques élémentaires

1) Tester les opérations élémentaires +, -, /, \*, \*\*, ainsi que // et % sur les entiers. Que réalisent ces 2 dernières opérations?

In [2]:
2+5

7

In [3]:
2-5

-3

In [4]:
4*6

24

In [5]:
4/7

0.5714285714285714

In [7]:
6//5

1

In [16]:
2**5

32

a//b donne le quotient de la division euclidienne de a par b

In [8]:
5%3

2

In [13]:
"""ceci est un commentaire """
1+1
3+7

10

Il est parfois utile de pouvoir afficher un ou plusieurs résultat avec la commande **print**.

In [15]:
print(3.14*12)
print(3)
print(3,2,"Hello!")
print(False, "trougzogu rzogu rzgo", 4.4)

37.68
3
3 2 Hello!
False trougzogu rzogu rzgo 4.4


## Le module numpy

On importe le module **numpy** avec la commande suivante :


In [21]:
import numpy as np

**as np** signifie que les fonctions de numpy sont appelés en utilisant le raccourci **np**.
On a par exemple une valeur approchée de pi dans ce module donnée par:

In [22]:
np.pi

3.141592653589793

On accède à l'ensemble des fonctions disponibles **numpy** par la commande

In [23]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

On appelle une fonction **fct** par la commande **np.fct**. On a par exemple:

In [32]:
np.cos(5)

0.28366218546322625

Pour accéder à l'aide de la fonction **abs** on utilisera **np.info(np.abs)** ou **help(np.abs)**. A noter qu'on peut utiliser l'auto-complétion avec la tabulation. Une description extensive des potentialités de ce module est disponible sur son site dédié
http://www.numpy.org/

In [28]:
np.info(np.abs)

absolute(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Calculate the absolute value element-wise.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
absolute : ndarray
    An ndarray containing the absolute value of
    each element in `x`.  For complex input, ``a + ib``, the
    absolute value is :math:`\sqr

## Les arrondis

2) Utiliser les fonctions **np.round** et **np.around**  pour arondir pi à 3.1415. Tester les fonctions **around** et **round**.

In [34]:
np.round(4.6666644357,3)

4.6669999999999998

In [45]:
help(np.round)

Help on function round_ in module numpy.core.fromnumeric:

round_(a, decimals=0, out=None)
    Round an array to the given number of decimals.
    
    Refer to `around` for full documentation.
    
    See Also
    --------
    around : equivalent function



Pour afficher moins de chiffres significatifs sans transformer le nombre, on peut utiliser:

In [48]:
print("{:.5f}".format(np.pi))

3.14159


<img src="https://media.giphy.com/media/LPBYImbgzsKpG/giphy.gif" width = 300>
<a id="2"></a> 
 
# 2. Variables et types

Déclaration = affection. On assigne à une variable **a** la valeur 1.234 avec:

In [49]:
a = 1.234
a

1.234

3) Créer une variable **b** contenant la valeur 5 et une variable **c** contenant la valeur **False**. Afficher le type de **a**, **b** et **c** avec la fonction **type**.

In [50]:
b = 5

In [119]:
c = False
c

False

In [121]:
c = 2>3
c

False

On peut forcer un changement de type en utilisant **int**, **float** ou **bool**. Par exemple :

In [53]:
int(c)

0

In [54]:
float(b)

5.0

In [55]:
int(a)

1

In [60]:
float("25236526.2462")

25236526.2462

## Opérations sur les variables

In [61]:
a*b - 3

3.17

In [62]:
c*a

0.0

In [63]:
b > 0

True

In [65]:
b > 0 and a <= 1

False

In [66]:
b > 0 or a <= 2

True

In [67]:
c != True

True

## Copies superficielle et profonde

In [71]:
a = [1,2]
b = a
b[0] = 2
(a,b)

([2, 2], [2, 2])

Copie superficielle

In [73]:
a = [4,2]
b = a.copy()
b[0] = 2
(a, b)

([4, 2], [2, 2])

Copie profonde

In [74]:
a = [[1, 2], [3]]
b = a.copy()
b[0][0] = 0
(a, b)

([[0, 2], [3]], [[0, 2], [3]])

In [75]:
import copy
a = [[1, 2], [3]]
b = copy.deepcopy(a)
b[0][0] = 0
(a, b)

([[1, 2], [3]], [[0, 2], [3]])

L'opération d'échange des variables **a** et **b** est réalisée par la commande

In [81]:
a = 3
b = 2
a,b = b,a

In [82]:
a

2

In [83]:
b

3

4) Réaliser l'échange des variables f = 5 et g = 6 en utilisant une varible temporaire temp.

In [84]:
f = 5
g = 6
print(f,g)
temp = f
f = g
g = temp
print(f,g)

5 6
6 5


## Chaînes de caractère

In [142]:
chaine = "Bonjour tout le monde !"

print(chaine)
chaine

Bonjour tout le monde !


'Bonjour tout le monde !'

In [86]:
age = 3
message = "J'ai " + str(age) + " ans."
print(message)

J'ai 3 ans.


In [87]:
len(chaine)


23

In [89]:
chaine+message

"Bonjour tout le monde !J'ai 3 ans."

In [90]:
chaine[0]

'B'

In [91]:
chaine[4]

'o'

In [92]:
chaine[3:7]

'jour'

In [94]:
chaine[3:-3]

'jour tout le mond'

In [98]:
chaine[0] = "b"
type(chaine)

TypeError: 'str' object does not support item assignment

5) Trouver une solution en utilisant la concaténation (+) pour "remplacer" le B initial par un b minuscule.

In [143]:
print(chaine)
chaine = "b"+chaine[1:]
chaine

Bonjour tout le monde !


'bonjour tout le monde !'

Comprendre ce que réalisent les commandes suivantes :

In [112]:
print(chaine)
chaine[-2::]

bonjour tout le monde !


' !'

In [113]:
chaine[::2]

'bnortu emne!'

In [138]:
chaine[2::2]

'nortu emne!'

In [79]:
chaine[::-2]

'!enme utronb'

In [125]:
"fichier"+str(2)

'fichier2'

 <img src="http://media.giphy.com/media/oGOW75SleZPR6/giphy.gif" width = 400>

 <a id="3"></a>
 
# 3. Conteneurs

## Les listes

Les listes = séquences = objets capables de contenir d'autres objets de n'importe quel type.

In [148]:
l = [1,False, "Hello!"]
l

[1, False, 'Hello!']

In [149]:
ma_liste = [1,1,2,3,5,8,13,21]
del ma_liste[0]
ma_liste

[1, 2, 3, 5, 8, 13, 21]

6) Supprimer l'élément en 4ème position dans ma_liste.

In [150]:
del ma_liste[3]
ma_liste

[1, 2, 3, 8, 13, 21]

Ajouter un élément en fin de liste avec **append**.

In [151]:
ma_liste.append(34)
ma_liste

[1, 2, 3, 8, 13, 21, 34]

In [152]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [153]:
max(l)

9

In [155]:
np.argmax(l)

9

In [156]:
np.argmax(ma_liste)

6

In [161]:
print(l)
l.pop(0)
l

[0, 1, 2, 3, 5, 6]


[1, 2, 3, 5, 6]

In [164]:
l.insert(6,55)
l

[1, 55, 55, 2, 3, 5, 55, 6]

In [153]:
l.insert(5,55)
l

[1, 55, 55, 55, 2, 55, 3, 4, 7, 8, 9]

In [166]:
56 in l

False

In [186]:
2*l

[1, 55, 55, 2, 3, 5, 55, 6, 1, 55, 55, 2, 3, 5, 55, 6]

In [187]:
ll = l + l 
ll[0:5]

[1, 55, 55, 2, 3]

Créer une liste contenant les valeurs 0, 10, 20 et 40 et l'inverser en une unique opération

In [191]:
[0,10,20,40][::-1]

[40, 20, 10, 0]

## Les t-uples

In [193]:
t = (1,1,2,False)
t

(1, 1, 2, False)

In [194]:
t.append(2)
t

AttributeError: 'tuple' object has no attribute 'append'

In [195]:
t[1] = 12

TypeError: 'tuple' object does not support item assignment

In [196]:
2 in t

True

In [197]:
t + t

(1, 1, 2, False, 1, 1, 2, False)

In [198]:
t[0::2]

(1, 2)

In [200]:
u = [1,2,3]
u

[1, 2, 3]

In [202]:
u[0] = 2
u

[2, 2, 3]

In [205]:
range(5)
print(list(range(5)))
len(range(5))

[0, 1, 2, 3, 4]


5

In [206]:
5 in range(5)

False

In [213]:
1 in range(5)

True

## Dictionnaires

In [214]:
monty_python = {'titre': 'Holy Grail', 'date': 1975}
monty_python

{'date': 1975, 'titre': 'Holy Grail'}

In [215]:
monty_python['traduction'] = 'Sacré Graal'
monty_python


{'date': 1975, 'titre': 'Holy Grail', 'traduction': 'Sacré Graal'}

In [216]:
monty_python["date"]

1975

In [217]:
monty_python.keys()

dict_keys(['titre', 'date', 'traduction'])

In [218]:
monty_python.values()

dict_values(['Holy Grail', 1975, 'Sacré Graal'])

In [219]:
monty_python.items()

dict_items([('titre', 'Holy Grail'), ('date', 1975), ('traduction', 'Sacré Graal')])

<img src="http://media1.giphy.com/media/7XlfU7Ol0cenS/200.gif#86-grid1" width = 400>
 
 <a id="4"></a>

# 4. Structures de contrôle

In [226]:
z = 0

if z < 1:
    print("z est plus petit que 1")
    print("z est plus petit que 1")
if z > 1: 
    print("z est plus grand que 1")

z est plus petit que 1
z est plus petit que 1


7) En utilisant **if**, **elif** et **else** contruire le code qui permet de dire (avec **print**) si une variable **a** est positive strictement, négative strictement ou nulle.

In [233]:
a = 0

if a < 0:
    print("a est négatif")
elif a > 0 : 
    print("a est positif")
else : 
    print("a est nul")

a est nul


Ci-dessous, nous donnons un exemple de code illustrant l'utilisation d'un **while**

In [238]:
nb = 7 # On garde la variable contenant le nombre dont on veut la table de multiplication
i = 0 # C'est notre variable compteur que nous allons incrémenter dans la boucle

while i < 10: # Tant que i est strictement inférieure à 10
    print(i + 1, "*", nb, "=", (i + 1) * nb)
    i += 1 # On incrémente i de 1 à chaque tour de boucle

1 * 7 = 7
2 * 7 = 14
3 * 7 = 21
4 * 7 = 28
5 * 7 = 35
6 * 7 = 42
7 * 7 = 49
8 * 7 = 56
9 * 7 = 63
10 * 7 = 70


Autre exemple avec une liste

In [240]:
ma_liste = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
i = 0 
while i < len(ma_liste):
    print(ma_liste[i])
    i += 1 

a
b
c
d
e
f
g
h


8) A l'aide d'une boucle **while** et d'un entier **N**, calculer la somme $\sum_{i=1}^N \frac{1}{i}$ pour $N = 100$ et $N = 1000$.

In [247]:
N = 100
i = 1
res = 0
while i < N+1:
    res = res + 1/i
    i = i+1
    
res

5.187377517639621

La boucle for fonctionne de la manière suivante :

In [252]:
chaine = "J'aime pas les maths"
for hrggfjg in chaine:
    print(hrggfjg)

J
'
a
i
m
e
 
p
a
s
 
l
e
s
 
m
a
t
h
s


Et de façon encore plus simple sur les entiers

In [255]:
for i in range(12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## Les exceptions

In [258]:
annee = input()
try: # On essaye de convertir l'année en entier
    annee = int(annee)
except:
    print("Erreur lors de la conversion de l'année.")

6426


<img src="https://media.giphy.com/media/13HgwGsXF0aiGY/giphy.gif" width = 300>
 
 
<a id="5"></a>
 
# 5. Fonctions

In [265]:
def table(nb, max=10):
    """Fonction affichant la table de multiplication par nb
    de 1*nb à max*nb
    (max >= 0)"""
    i = 0
    while i < max:
            print(i + 1, "*", nb, "=", (i + 1) * nb)
            i += 1

table(6,4)

1 * 6 = 6
2 * 6 = 12
3 * 6 = 18
4 * 6 = 24


In [266]:
def carre(valeur):
    return valeur * valeur

carre(12)

144

On va utiliser la constante gamma d'Euler-Mascheroni. Elle est disponible dans **numpy**. Se reporter à https://fr.wikipedia.org/wiki/Constante_d%27Euler-Mascheroni pour des explications sur cette constante

In [269]:
np.euler_gamma


0.5772156649015329

In [270]:
em = np.euler_gamma
em

0.5772156649015329

9) Créer une fonction qui donne la différence entre la somme harmonique jusqu'à $N$ et $log(N)$. Comparer cette valeur à la constante d'Euler-Mascheroni pour différence valeur de N.

In [280]:

def Euler(N):
    i = 1
    res = 0
    while i < N+1:
        res = res + 1/i
        i = i+1
    return (res - np.log(N))

em2 = Euler(10000000)
print(em)
print(em2)
em2 - em

0.5772156649015329
0.577215714899


4.99974185386165e-08

<img src="http://media2.giphy.com/media/6MMxtt269tcAM/giphy.gif" width = 300>


<a id="6"></a>

# 6. Introduction à numpy

In [284]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [288]:
a.shape

(4, 5)

In [289]:
a.ndim

2

In [290]:
a.size

20

In [292]:
a[1,1]

6

In [308]:
a[1,1] - 3
a

array([[ 0,  1,  2,  3,  4],
       [ 5, -3,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [320]:
b = np.array([(1.5,2,3), (4,5,6)])
b[:,1] = np.array([(1,2)])
b

array([[ 1.5,  1. ,  3. ],
       [ 4. ,  2. ,  6. ]])

In [300]:
b-2*b + np.sin(b)

array([[-0.50250501, -1.09070257, -2.85887999],
       [-4.7568025 , -5.95892427, -6.2794155 ]])

In [301]:
np.sqrt(b)

array([[ 1.22474487,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [302]:
np.sin(b)

array([[ 0.99749499,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [303]:
b-3

array([[-1.5, -1. ,  0. ],
       [ 1. ,  2. ,  3. ]])

Remarque

In [304]:
[1,2,4]-1

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [305]:
(1,2,4)-1

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'

In [322]:
np.linspace(0, 10, 11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [323]:
np.zeros((4,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [324]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [327]:
M=np.mat('[1 2 4 ; 3 4 5.]')
N=np.mat('[2. ; 4 ; 6]')
print(M)
print(N)

[[ 1.  2.  4.]
 [ 3.  4.  5.]]
[[ 2.]
 [ 4.]
 [ 6.]]


In [329]:
M.T

matrix([[ 1.,  3.],
        [ 2.,  4.],
        [ 4.,  5.]])

In [356]:
import time

In [362]:
X = np.mat([range(10000000)])
Y = np.mat([range(10000000)]).T

In [366]:
debut = time.time()
W = X*Y
fin = time.time()
res1 = fin-debut
res1

0.0

In [367]:
debut = time.time()
res = 0
for i in range(1000000):
    res = res + i*i
fin = time.time()
res2 = fin-debut
res2

0.1406092643737793

In [369]:
res2/res1

ZeroDivisionError: float division by zero

10) Créer une matrice carré M de taille 10x10 dont l'élément en position (i,j) vaut i+j

Tester les opérations suivantes: M.sum(), M.cumsum(), M.mean(). Extraire une sous-matrice de votre choix.

<img src="https://media.tenor.co/images/b23259c73fefcf5ba4b2162e482763e8/raw" width = 300>

